name: Build PyInstaller Executables

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.11] 
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      # Installing pyinstaller separately, then installing all project dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Run PyInstaller
      run: pyinstaller --onefile temp_calc.py
      
      
    - name: Rename and compress executable for Windows
      if: runner.os == 'Windows'
      # PowerShell commands for renaming and zipping the file
      run: |
        Rename-Item dist\temp_calc.exe temp_calc_windows.exe
        Compress-Archive -Path temp_calc_windows.exe -DestinationPath temp_calc_windows.zip
        
    - name: Rename and compress executable for macOS
      if: runner.os == 'macOS'
      # Bash commands for renaming and zipping the file
      run: |
        mv dist/temp_calc temp_calc_macos
        zip -r temp_calc_macos.zip temp_calc_macos
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: standalone-executables
        path: |
          temp_calc_windows.zip
          temp_calc_macos.zip
